#!/bin/sh
#
#  <functions>
#    Copyright 2008 James Cook - All Rights Reserved.
#
#

# create a "which"-like function, because 'which -s' isn't available
# everywhere, and the redirects are annoying
if which _this_name_better_not_exist_ > /dev/null; then
	# which is not reliable; use alternate means
	if which _this_name_better_not_exist_ | grep -qv '^/'; then
		function cmdExists {
			which "$@" | grep -q '^/'
		}
	else
		echo Warning: don\'t know how to make a reliable \"cmdExists\"
		echo function on this system.  Making a dummy that always fails.

		function cmdExists {
			false
		}
	fi
else
	# which is ok, use it
	function cmdExists {
		which "$@" > /dev/null
	}
fi

#
# Read user's functions
#
if [ -r "${user_bash_initdir}/functions" ]; then
	source "${user_bash_initdir}/functions"
fi
