#!/bin/sh

deepbondi="${deepbondi:-/deepbondi}"

if [ -d "$deepbondi" ]; then
	cat "$deepbondi/etc/motd.header" > /etc/motd
	"$deepbondi/bin/motd" >> /etc/motd

	cat "$deepbondi/etc/motd.irc.header" /etc/motd "$deepbondi/etc/rules" > /etc/motd.irc
else
	echo Neither \$deepbondi nor /deepbondi is a directory.  I\'m scared\!
fi