<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.cf</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>LBNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pragma</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>category</key>
		<dict>
			<key>name</key>
			<string>entity.name.type.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#reserved.categories</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z][A-Za-z0-9_]*</string>
					<key>name</key>
					<string>entity.name.category.lbnf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.square-bracket.begin.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.square-bracket.end.lbnf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#category</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment.line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment.block</string>
				</dict>
			</array>
		</dict>
		<key>comment.block</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>comment.block.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment.block.content</string>
				</dict>
			</array>
		</dict>
		<key>comment.block.content</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>meta.nested.comment.block.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment.block.content</string>
				</dict>
			</array>
		</dict>
		<key>comment.line</key>
		<dict>
			<key>begin</key>
			<string>(--)[ -]?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-dash.lbnf</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z][A-Za-z0-9_]+</string>
			<key>name</key>
			<string>entity.name.identifier.lbnf</string>
		</dict>
		<key>label</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal.char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal.integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal.string</string>
				</dict>
			</array>
		</dict>
		<key>literal.char</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\'</string>
					<key>name</key>
					<string>constant.character.escape.lbnf</string>
				</dict>
			</array>
		</dict>
		<key>literal.integer</key>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.lbnf</string>
		</dict>
		<key>literal.string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.lbnf</string>
				</dict>
			</array>
		</dict>
		<key>pragma</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(comment)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.comment.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.comment.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#literal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(internal)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.internal.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=;)</string>
					<key>name</key>
					<string>pragma.internal.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rule</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b((?:position\s+)?token)(?:\s+([A-Za-z][A-Za-z0-9_]*))?\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.token.lbnf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.category.lbnf</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.list.regexp.lbnf</string>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.token.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#token.reg</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(entrypoints)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.entrypoints.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.entrypoints.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#category</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b((?:separator|terminator)(?:\s+nonempty)?)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.separator.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.separator.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#category</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#literal.string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(coercions)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.coercions.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.coercions.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#category</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#literal.integer</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(rules)(?:\s+([A-Za-z][A-Za-z0-9_]*))?\b(?:\s*(::=))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.rules.lbnf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.category.lbnf</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.double-colon-equals.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.rules.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rules.rhs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(layout(?:\s+(?:stop|toplevel))?)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.pragma.layout.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.semicolon.lbnf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>pragma.layout.lbnf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#literal.string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>production</key>
		<dict>
			<key>name</key>
			<string>meta.production.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#category</string>
				</dict>
			</array>
		</dict>
		<key>reserved.categories</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>Double</string>
					<key>name</key>
					<string>support.label.double.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>Integer</string>
					<key>name</key>
					<string>support.label.integer.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bChar\b</string>
					<key>name</key>
					<string>support.label.char.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bString\b</string>
					<key>name</key>
					<string>support.label.string.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIdent\b</string>
					<key>name</key>
					<string>support.label.ident.lbnf</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>([A-Za-z][A-Za-z0-9_]+)|(\[\]|\(:\)|\(:\[\]\))|(_)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.label.lbnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.list.label.lbnf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.label.wildcard.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.semicolon.lbnf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule.part.cat</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule.part.production</string>
				</dict>
			</array>
		</dict>
		<key>rule.part.cat</key>
		<dict>
			<key>begin</key>
			<string>(\.)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.period.lbnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>meta.rule.part.cat.lbnf</string>
			<key>end</key>
			<string>(?=::=)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#category</string>
				</dict>
			</array>
		</dict>
		<key>rule.part.production</key>
		<dict>
			<key>begin</key>
			<string>(::=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.double-colon-equals.lbnf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>meta.rule.part.production.lbnf</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#production</string>
				</dict>
			</array>
		</dict>
		<key>rules.rhs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>operator.separator.rules.lbnf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal.string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#category</string>
				</dict>
			</array>
		</dict>
		<key>token.reg</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal.char</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>constant.language.token.lbnf</string>
					<key>match</key>
					<string>\b(eps|digit|letter|upper|lower)\b</string>
					<key>name</key>
					<string>string.regexp.token.lbnf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.parentheses.begin.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.parentheses.end.lbnf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#token.reg</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.square-bracket.begin.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.square-bracket.end.lbnf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literal.string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.brace.begin.lbnf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.brace.end.lbnf</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literal.string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[|\-*+?]</string>
					<key>name</key>
					<string>operator.regex.token.lbnf</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lbnf</string>
	<key>uuid</key>
	<string>0E5AAA2A-4893-41C6-8D74-B925FE2633EF</string>
</dict>
</plist>
