<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.cf</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>LBNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved.words</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockComment</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>comment.block.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockCommentContent</string>
				</dict>
			</array>
		</dict>
		<key>blockCommentContent</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>meta.nested.comment.block.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockCommentContent</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dashComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
			</array>
		</dict>
		<key>dashComment</key>
		<dict>
			<key>begin</key>
			<string>(--)[ -]?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-dash.lbnf</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z][A-Za-z0-9_]+</string>
			<key>name</key>
			<string>entity.name.identifier.lbnf</string>
		</dict>
		<key>label</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
			</array>
		</dict>
		<key>literal.char</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\'</string>
					<key>name</key>
					<string>constant.character.escape.lbnf</string>
				</dict>
			</array>
		</dict>
		<key>literal.integer</key>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.lbnf</string>
		</dict>
		<key>literal.string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.lbnf</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal.char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal.integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal.string</string>
				</dict>
			</array>
		</dict>
		<key>reserved.labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b_\b</string>
					<key>name</key>
					<string>support.label.wildcard.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>Double</string>
					<key>name</key>
					<string>support.label.double.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>Integer</string>
					<key>name</key>
					<string>support.label.integer.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bChar\b</string>
					<key>name</key>
					<string>support.label.char.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bString\b</string>
					<key>name</key>
					<string>support.label.string.lbnf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIdent\b</string>
					<key>name</key>
					<string>support.label.ident.lbnf</string>
				</dict>
			</array>
		</dict>
		<key>reserved.symbols</key>
		<dict>
			<key>match</key>
			<string>::=|[;.\[\]_():,|\-*+?\{\}]</string>
			<key>name</key>
			<string>keyword.operator.lbnf</string>
		</dict>
		<key>reserved.words</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(char|coercions|comment|digit|entrypoints|eps|internal|layout|letter|lower|nonempty|position|rules|separator|stop|terminator|token|toplevel|upper)\b</string>
					<key>name</key>
					<string>keyword.other.lbnf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserved.labels</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>([A-Za-z][A-Za-z0-9_]+)|(\[\]|\(:\))\s*(\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.label.lbnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.list.label.lbnf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.period.rule-thingy.lbnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>name</key>
			<string>meta.rule.lbnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lbnf</string>
	<key>uuid</key>
	<string>0E5AAA2A-4893-41C6-8D74-B925FE2633EF</string>
</dict>
</plist>
